#200 Refresh Token Rotation does not update cookie if called server s…
sidebase/nuxt-auth pull request #215
Opened 2023-02-06 10:39 UTC by vanling

Copied the small proposal for a fix for #200 from @ayalon, applied his fix locally and the JWT cookie was updated correctly everytime.

I have no understanding of how 90% of this all works, so this fix might require some more testing with other providers.

Closes #200  .

Checklist:
- [*] issue number linked above after pound (`#`)
- [*] manually checked my feature / checking not applicable
- [ ] wrote tests / testing not applicable
- [ ] attached screenshots / screenshot not applicable

2023-02-06 14:29 UTC, BracketJohn requested changes
Hey @vanling 👋 

Thanks for the PR and taking up this work 💯 


> I have no understanding of how 90% of this all works, so this fix might require some more testing with other providers.

I think for now this is fine: It only adds some cookie setting, so the change should work independent of different providers.

One nit and we're good to go

2023-02-06 14:33 UTC, BracketJohn commented
Also, please resolve the open TS errors:
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/25911230/216998704-dd0399aa-16ce-428e-a8cb-329e779d94fe.png">

Test locally by running:
```sh
npm run types
```

2023-02-06 14:41 UTC, vanling commented
That is going to be an adventure 😂 I will have a try at it tonight =)

2023-02-06 14:44 UTC, BracketJohn commented
Sure thing. Should be straightforward and if it isn't let me know and I can give you a hand. Basically there's two errors:
1. `nuxt.ssrContext` may be undefined -> resolve it by checking if it exists
2. `setCookieValue` may be undefined -> resolve this by also checking if it exists before assigning it

So, easy enough 😄

2023-02-06 18:44 UTC, ayalon commented
I have fixed the typescript error. Thanks for the collaboration on this issue. Highly appreciated.

2023-02-06 18:54 UTC, vanling commented
Thanks @ayalon I am happy you joined in this one :D did not want to steal al your credits ;)

2023-02-07 12:03 UTC, ayalon commented
The tests legitimately failed. Awesome coverage. I have fixed the missing import. Let's see if this works.

2023-02-07 17:02 UTC, BracketJohn requested changes

2023-02-07 17:02 UTC, BracketJohn commented on src/runtime/composables/useSession.ts
> +      }
I think we can improve this a bit:
```suggestion
      // Add any new cookie to the server-side event for it to be present on the app-side after
      // initial load, see sidebase/nuxt-auth/issues/200 for more information.
      if (process.server) {
        const setCookieValue = response.headers.get('set-cookie')
        if (setCookieValue && nuxt.ssrContext) {
          appendHeader(nuxt.ssrContext.event, 'set-cookie', setCookieValue)
        }
      }
```

2023-02-07 17:02 UTC, BracketJohn commented
> The tests legitimately failed. Awesome coverage. I have fixed the missing import. Let's see if this works.

thanks, this is an awesome compliment. Just reviewed tyour code (:

2023-02-07 20:59 UTC, vanling commented
Changed the import order, ran lint + types local. Should be ok now.

2023-02-08 08:44 UTC, BracketJohn approved these changes

2023-02-08 08:44 UTC, merged