fix: Cannot access 'renderer' before initialization. (#420)
sidebase/nuxt-auth pull request #490
Opened 2023-07-20 15:30 UTC by Eternal-Grace

The value of `'authjs'` was hard coded in the file at :
`@sidebase/nuxt-auth/dist/runtime/server/services/authjs/nuxtAuthHandler.mjs` generating an error whenever `auth.provider.type = 'local'` was used.

This fork's aim is to fix this issue.

2023-07-26 14:06 UTC, zoey-kaiser approved these changes
LGTM

2023-08-01 12:23 UTC, Eternal-Grace commented
The `typecheck` failed to execute itself on codes not related to the issue.
It means that someone, somehow, pushed an un-typechecked code...
Making this merge request, difficult to proceed.
https://github.com/sidebase/nuxt-auth/actions/runs/5724583013/job/15514116059?pr=490

... Do I attempt to refactor the following files:
```log
1  src/runtime/composables/commonAuthState.ts:36
2  src/runtime/helpers.ts:31
3  src/runtime/middleware/auth.ts:51
2  src/runtime/plugin.ts:16
5  src/runtime/server/services/authjs/nuxtAuthHandler.ts:23
2  src/runtime/server/services/utils.ts:19
1  src/runtime/utils/url.ts:56
```
Or do I wait for someone else to do it?

2023-08-01 15:46 UTC, zoey-kaiser commented
@Eternal-Grace,

I have managed to identify the issue! When you added support for different provider types, the `useConfig()` function could either return the `authJS` or `local` schema. The `local` schema, however does not include properties such as `trustHost`, leading to the type issues. 
I assume you would need to add some checks to ensure that the code for authJS only runs when the selected providor is authjs. 

See example here: https://github.com/GenitusTech/nuxt-auth/blob/main/src/runtime/server/services/authjs/nuxtAuthHandler.ts#L80

2023-08-11 17:54 UTC, Eternal-Grace commented
@zoey-kaiser 
Ok, it is done. Can you approve, so that we can proceed?
( https://github.com/sidebase/nuxt-auth/pull/490/commits/8a1866d6fc9f4857cf128433ffb69b14c17344e7 )

2023-08-15 09:44 UTC, zoey-kaiser requested changes

2023-08-15 09:44 UTC, zoey-kaiser commented on src/runtime/server/services/authjs/nuxtAuthHandler.ts
> +const useConfig = () => useTypedBackendConfig(useRuntimeConfig(), useRuntimeConfig().public.auth.provider.type ?? 'authjs')
```suggestion
const provider = useRuntimeConfig().public.auth.provider.type ?? 'authjs'
const useConfig = () => useTypedBackendConfig(useRuntimeConfig(), provider)
```

2023-08-15 09:44 UTC, zoey-kaiser commented on src/runtime/server/services/authjs/nuxtAuthHandler.ts
> +    trustHost: useConfig()?.trustHost ?? false
```suggestion
trustHost: provider === 'authjs' ? useConfig().trustHost : false
```

2023-08-15 09:44 UTC, zoey-kaiser commented
Lets see if the two changes I recommended would work!

2023-08-15 17:46 UTC, Eternal-Grace commented
Thanks for the changes. Now, let's hope this "Bug Arc" comes to an end at last =_=)

2023-08-16 11:12 UTC, Eternal-Grace commented
Danm! This is beyond stressful: https://github.com/sidebase/nuxt-auth/actions/runs/5870155610/job/15938032936?pr=490
Job failed, once again. -_-')
Any suggestions @zoey-kaiser ?

2023-08-17 10:27 UTC, zoey-kaiser commented
> Danm! This is beyond stressful: [sidebase/nuxt-auth/actions/runs/5870155610/job/15938032936?pr=490](https://github.com/sidebase/nuxt-auth/actions/runs/5870155610/job/15938032936?pr=490) Job failed, once again. -_-') Any suggestions @zoey-kaiser ?

Ill have to play around with it a bit myself! I don't have time today, but ill try and give it a shot tomorrow.

2023-10-11 10:39 UTC, zoey-kaiser commented
@Eternal-Grace, please see my comment https://github.com/sidebase/nuxt-auth/issues/420#issuecomment-1757373955 on how we can continue working on your problem. 

For now, I will close this PR, as I think we approached this issue incorrectly! If you are still interested in working with me to resolve this, please open a new issue with more details about the issue you ran into + logs and I will look into another solution!

2023-10-11 10:39 UTC, closed without merging