feat: added token, refreshToken cookieName option
sidebase/nuxt-auth pull request #654
Opened 2024-02-02 12:48 UTC by FAL-coffee

Closes #650 .

---
Allow the user to change the property name where tokens are stored in the cookie when using local or refresh types.

---
**Why this is needed:**
 Conflicts occur with where tokens are stored when multiple environments are launched on localhost.
It also solves the problem that issue #650 refers to.

---
Checklist:
- [ ] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [ ] manually checked my feature / checking not applicable
- [ ] wrote tests / testing not applicable
- [ ] attached screenshots / screenshot not applicable

2024-02-08 16:08 UTC, phoenix-ru approved these changes

2024-02-08 16:10 UTC, phoenix-ru commented
Looks good to me.
@zoey-kaiser OP is right in #650, should we use `auth.token` and `auth.refresh-token` as default cookie names instead?

2024-02-08 16:14 UTC, FAL-coffee commented
> Looks good to me. @zoey-kaiser OP is right in #650, should we use `auth.token` and `auth.refresh-token` as default cookie names instead?

In my personal opinion, changing the default CookieName could pose a risk of logging users out across all existing services when updating the library version. 
Additionally, since restrictions only apply in certain cases, I believe it is unnecessary to change the default CookieName.

2024-02-22 16:52 UTC, phoenix-ru requested changes

2024-02-22 16:52 UTC, phoenix-ru commented on docs/content/2.configuration/2.nuxt-config.md
> +     * @default auth:token
Please, change `auth:token` to `auth.token` everywhere

2024-02-22 16:52 UTC, phoenix-ru commented on src/module.ts
> +      cookieName: 'auth:refresh-token',
Do the same for `auth:refresh-token`

2024-02-22 16:54 UTC, phoenix-ru commented
@FAL-coffee I have functionally tested your changes. Please, address the review and it can be safely merged.

2024-02-22 17:28 UTC, FAL-coffee commented
@phoenix-ru 
I have committed the change to switch the default delimiter from ':' to '.'!

2024-02-29 09:08 UTC, phoenix-ru approved these changes

2024-02-29 09:09 UTC, merged