chore: upgrade to nitro 2.10, preparing for nitropack ecosystem switch from `nitropack` to `nitro`
sidebase/nuxt-auth pull request #942
Opened 2024-11-12 10:45 UTC by BracketJohn

…

### 🔗 Linked issue

N/A

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR upgrades `nitropack@2.9.7` to `nitropack@2.10.4`. This resolves two issues:
- existing: `nitropack@2.9.7` relies on an unimport-version that augments the vue-runtime-core types, which was deprecated with vue 3.5: https://github.com/unjs/unimport/pull/359
- upcoming: `nitropack@2.10.4` changes the package structure for an upcoming switch to the new name `nitro` with the release of `v3`. So if people upgrade to latest nuxt and in turn also upgrade all sub-deps to latest nitro, the import that `nuxt-auth` has from `nitropack` will break (see changes I made here)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have added tests (if possible).
- [ ] I have updated the documentation accordingly.

2024-11-12 11:01 UTC, BracketJohn commented
@phoenix-ru / @zoey-kaiser: Opening this to raise awareness of the above potential issues. Feel free to merge as is / close / put into another dep-upgrade PR.

2024-11-12 11:32 UTC, zoey-kaiser approved these changes

2024-11-14 08:25 UTC, phoenix-ru requested changes
There are multiple duplicate packages in the lockfile (majority wasn't duplicated prior to this PR)

At the very least it will cause undefined behaviour when developing `nuxt-auth`.

@BracketJohn which command did you use to update `nitropack`? I think a deduplication run needs to happen on the lockfile

2024-12-12 17:07 UTC, phoenix-ru approved these changes

2024-12-12 17:07 UTC, merged